version: '3'

services:
  auth:
    container_name: auth
    build:
      args:
        user: ${AUTH_USER}
        uid: 1000
      context: images/php
      dockerfile: Dockerfile
    volumes:
      - ./${AUTH_PATH}:/var/www/html
    working_dir: /var/www/html
    command: php-fpm
    links:
      - db:db
    ports:
      - '${AUTH_PORT}:9000'
    depends_on:
      - db

  nginx:
    container_name: nginx
    build: images/nginx
    command: nginx -g "daemon off;"
    links:
      - auth
    ports:
      - '${NGINX_PORT}:80'
    depends_on:
      - db

  db:
    container_name: mysql
    image: mysql:8
    restart: always
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - './.docker/mysql/database:/var/lib/mysql'
