version: '3'

services:
  auth-service:
    container_name: auth-service
    build:
      args:
        user: ${USERNAME}
        uid: 1000
      context: images/php
      dockerfile: Dockerfile
    volumes:
      - ./${SERVICE_NAME}:/var/www/html
    working_dir: /var/www/html
    command: php-fpm
    links:
      - db:db
    ports:
      - '9000:9000'
    depends_on:
      - db

  nginx:
    container_name: nginx
    build: images/nginx
    command: nginx -g "daemon off;"
    links:
      - auth-service
    ports:
      - '8080:80'
    depends_on:
      - db

  db:
    container_name: mysql
    image: mysql:8
    restart: always
    ports:
      - '33066:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - './.docker/mysql/data:/var/lib/mysql'
