version: '3'

services:
  api-service:
    container_name: api-service
    build:
      args:
        user: thiago
        uid: 1000
      context: images/php
      dockerfile: Dockerfile
    volumes:
      - ./api-service:/var/www/html
    working_dir: /var/www/html
    command: php-fpm
    links:
      - db:db
    ports:
      - '9000:9000'
    depends_on:
      - db

  nginx:
    container_name: nginx
    build: images/nginx
    command: nginx -g "daemon off;"
    links:
      - api-service
    ports:
      - '8001:80'
    depends_on:
      - db

  db:
    container_name: mysql
    image: mysql:8
    restart: always
    ports:
      - '33067:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - './.docker/mysql:/var/lib/mysql'
